apiVersion: v1
kind: Service
metadata:
  name: vllm-llama-service
spec:
  selector:
    app: vllm-llama
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort  # We can use LoadBalancer for production
